remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

title: Agricultural Zoning ML Documentation
description: Precision agriculture zoning and vegetation index analysis system

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/australmetrics/agricultural-zoning-ml

# Just the Docs settings
aux_links:
  "Ver en GitHub":
    - "https://github.com/australmetrics/agricultural-zoning-ml"

search_enabled: true
