theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

title: Agricultural Zoning ML Documentation
description: Precision agriculture zoning and vegetation index analysis system

# Navigation
header_pages:
  - index.md
  - user_guide/quick_start.md
  - user_guide/user_guide.md
  - technical/api_documentation.md
  - technical/architecture_overview.md
  - examples/basic_usage.md
  - examples/advanced_examples.md

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/australmetrics/agricultural-zoning-ml

# Additional settings
show_downloads: true

