name: 📦 Release on Tag

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## 🚀 Release ${{ github.ref_name }}
            
            **AustralMetrics - AgTech Solutions**
            
            ### ✅ Cambios incluidos:
            - Tests passing  
            - Lint & type-check OK
            - Verificación ISO 42001 completa
            
            ### 📋 Instrucciones de instalación:
            ```bash
            git clone https://github.com/australmetrics/agricultural-zoning-ml.git
            cd agricultural-zoning-ml
            git checkout ${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
